services:
    mediamtx:
        image: ghcr.io/netsocs-team/mediamtx_with_persistence/main:latest
        network_mode: host
        volumes:
            - ./recordings:/recordings:rw
            - ./mediamtx:/etc/mediamtx
