#!/bin/sh

# Run mediamtx_persistence in the background
echo "Running mediamtx_persistence in the background..."
echo "The logs are available at /opt/startup/persistence.log"
/opt/startup/persistence --config=/etc/mediamtx/mediamtx.yaml --mediamtx=http://localhost:9997 > /opt/startup/persistence.log 2>&1 &

# Run mediamtx
echo "Running mediamtx..."

# if /etc/mediamtx.yaml not exist, copy /opt/startup/mediamtx.yaml to /etc/mediamtx.yaml
if [ ! -f /etc/mediamtx/mediamtx.yaml ]; then
    echo "Copying /opt/startup/mediamtx.yaml to /etc/mediamtx/mediamtx.yaml"
    cp /opt/startup/mediamtx.yaml /etc/mediamtx/mediamtx.yaml
fi

/mediamtx /etc/mediamtx/mediamtx.yaml
