#!/bin/sh

# Run mediamtx_persistence in the background
echo "Running mediamtx_persistence in the background..."
echo "The logs are available at /opt/startup/persistence.log"
/opt/startup/persistence --config=/opt/startup/mediamtx.yaml > /opt/startup/persistence.log 2>&1 &

# Run mediamtx
echo "Running mediamtx..."
/mediamtx /opt/startup/mediamtx.yaml