name: Build and Package Driver

on:
    push:
        branches:
            - main
            - engine_as_driver
    pull_request:

jobs:
    build-and-package-driver:
        runs-on: ubuntu-22.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.24.x'

            - name: Build persistence binary
              run: |
                  go env -w CGO_ENABLED=0
                  go version
                  # Build main package into ./persistence
                  go build -trimpath -ldflags "-s -w" -o persistence .
                  file persistence

            - name: Download MediaMTX binary from S3 (linux amd64)
              run: |
                  set -euo pipefail
                  URL="https://netsocs-public-drivers-repository.s3.us-east-1.amazonaws.com/video_engine_mediamtx/mediamtx"
                  echo "Downloading MediaMTX from: $URL"
                  mkdir -p bin
                  curl -fL "$URL" -o ./bin/mediamtx
                  chmod +x ./bin/mediamtx
                  ./bin/mediamtx --version || true

            - name: Prepare package contents
              run: |
                  mkdir -p recordings
                  mkdir -p mediamtx
                  # Optionally include a placeholder .gitkeep so empty dirs are zipped
                  touch recordings/.gitkeep
                  touch mediamtx/.gitkeep

            - name: Create zip package
              run: |
                  PACKAGE_NAME=mediamtx_with_persistence.zip
                  rm -f "$PACKAGE_NAME"
                  zip -r "$PACKAGE_NAME" persistence bin/mediamtx recordings mediamtx
                  ls -lah "$PACKAGE_NAME"
                  echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

            - name: Upload to S3
              uses: hkusu/s3-upload-action@v2
              with:
                  aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-bucket: ${{ secrets.AWS_DRIVER_BUCKET }}
                  aws-region: us-east-1
                  file-path: ${{ env.PACKAGE_NAME }}
                  destination-dir: /
                  bucket-root: /


