name: Build and Release

on:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: mediamtx_with_persistence

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go 1.24
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24"
            - name: Build
              run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o mediamtx_persistence
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "mediamtx_persistence"
                  tag: v1.1.0
            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker Build and Push
              uses: docker/build-push-action@v6
              with:
                  platforms: linux/amd64
                  provenance: false
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/netsocs-team/${{ env.IMAGE_NAME }}/main:latest
                      ${{ env.REGISTRY }}/netsocs-team/${{ env.IMAGE_NAME }}/main:${{ github.sha }}
