name: Build and Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go 1.24
              uses: actions/setup-go@v5
              with:
                  go-version: "1.24"
            - name: Build
              run: go build -ldflags "-X main.version=${GITHUB_SHA}" -o mediamtx_persistence
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "mediamtx_persistence"
                  tag: v1.0.0
